// @ts-nocheck
import { db } from '$lib/db/mockDb';
import { supabase, withTimeout } from '$lib/supabase';
import { globalStore } from '$lib/stores/globalStore.svelte';

/**
 * Automatically creates a Vendor Tax Invoice after successful Razorpay payment
 * and dispatches it with notifications to Admin and Managers.
 *
 * @param {Object} params
 * @param {string} params.poNumber - e.g. PO-2026-0001
 * @param {string} params.vendorId - Vendor ID
 * @param {string} [params.vendorName] - Vendor display name
 * @param {number} params.amount - Total amount paid in INR
 * @param {string} params.paymentId - Razorpay Payment ID (e.g. pay_xxx)
 * @param {string} [params.requestId] - Associated purchase request ID
 * @param {string} [params.description] - Description of items or contract
 * @param {Object} [params.currentUser] - The user who initiated the action
 * @returns {Promise<{ success: boolean, invoice?: Object, error?: string }>}
 */
export async function createAndSendVendorInvoice({
	poNumber,
	vendorId,
	vendorName,
	amount,
	paymentId,
	requestId = '',
	description = '',
	currentUser = null
}) {
	try {
		// 1. Resolve vendor details
		const vendors = db.getVendors() || [];
		const matchedVendor = vendors.find(
			(v) => v.id === vendorId || v.vendorId === vendorId
		);

		const resolvedVendorName =
			vendorName ||
			matchedVendor?.name ||
			matchedVendor?.company_name ||
			matchedVendor?.companyName ||
			(vendorId === 'vendor-1' ? 'Demo Technologies' : 'Vendor Partner');

		// 2. Generate unique invoice number
		const currentYear = new Date().getFullYear();
		const existingInvoices = db.getInvoices() || [];
		const yearInvoices = existingInvoices.filter(
			(inv) => typeof inv.invoiceNumber === 'string' && inv.invoiceNumber.startsWith(`INV-${currentYear}-`)
		);
		const nextInvNumber =
			'INV-' +
			currentYear +
			'-' +
			String(yearInvoices.length + 101).padStart(4, '0');

		// 3. Tax & Subtotal calculation (18% GST standard)
		const totalAmount = Number(amount) || 0;
		const subtotal = Math.round((totalAmount / 1.18) * 100) / 100;
		const taxAmount = Math.round((totalAmount - subtotal) * 100) / 100;
		const invoiceId = 'inv-' + Math.random().toString(36).substring(2, 9);
		const timestamp = new Date().toISOString();

		// 4. Construct complete invoice record
		const newInvoice = {
			id: invoiceId,
			invoiceNumber: nextInvNumber,
			invoice_number: nextInvNumber,
			poNumber: poNumber,
			po_number: poNumber,
			vendorId: vendorId,
			vendor_id: vendorId,
			vendorName: resolvedVendorName,
			vendorEmail: matchedVendor?.email || 'vendor@procurement.com',
			vendorPhone: matchedVendor?.phone || '+91-9876543210',
			vendorAddress: matchedVendor?.address || 'Industrial Estate, Phase 2',
			amount: totalAmount,
			subtotal: subtotal,
			taxAmount: taxAmount,
			currency: 'INR',
			status: 'Paid',
			paymentId: paymentId || `pay_sim_${Date.now()}`,
			payment_id: paymentId || `pay_sim_${Date.now()}`,
			paymentMethod: 'Razorpay',
			paymentStatus: 'Settled',
			submittedAt: timestamp,
			paidAt: timestamp,
			verifiedAt: timestamp,
			verifiedById: currentUser?.id || 'admin',
			sentToAdmin: true,
			sentToAdminAt: timestamp,
			requestId: requestId,
			description: description || `Contract order supply under ${poNumber}`,
			notes: `Automated Tax Invoice generated by vendor (${resolvedVendorName}) upon instant Razorpay settlement (${paymentId}). Dispatched to Admin for records.`,
			attachmentUrl: `/invoices/${nextInvNumber}.pdf`
		};

		// 5. Save to local store
		existingInvoices.unshift(newInvoice);
		db.saveInvoices(existingInvoices);

		// 6. Attempt non-blocking Supabase sync
		try {
			await withTimeout(
				supabase.from('invoices').insert({
					id: invoiceId,
					po_number: poNumber,
					invoice_number: nextInvNumber,
					vendor_id: vendorId,
					amount: totalAmount,
					status: 'Paid',
					payment_id: paymentId,
					paid_at: timestamp,
					submitted_at: timestamp
				}),
				1500
			);
		} catch (supaErr) {
			console.warn('Supabase invoice insert warning (fallback to local db):', supaErr);
		}

		// 7. Dispatch notification to Admin and Managers
		try {
			const users = db.getUsers() || [];
			const adminUsers = users.filter(
				(u) => u.role === 'Manager' || u.role === 'Admin' || u.id === 'user-mgr1'
			);

			adminUsers.forEach((admin) => {
				db.addNotification(
					admin.id,
					'Vendor Invoice Received (Paid)',
					`Vendor ${resolvedVendorName} has generated and submitted Paid Tax Invoice ${nextInvNumber} for ${poNumber} (₹${totalAmount.toLocaleString()}). Payment verified via Razorpay (${paymentId}). Sent to Admin for accounting records.`,
					'Success'
				);
			});

			// Notify vendor user as well for their records
			const vendorUsers = users.filter((u) => u.vendorId === vendorId);
			vendorUsers.forEach((vu) => {
				db.addNotification(
					vu.id,
					'Invoice Dispatched to Admin',
					`Your Tax Invoice ${nextInvNumber} for PO ${poNumber} (₹${totalAmount.toLocaleString()}) was successfully settled via Razorpay (${paymentId}) and dispatched to Admin.`,
					'Success'
				);
			});

			// Reload current user's notification list
			if (currentUser?.id && typeof globalStore.loadNotifications === 'function') {
				globalStore.loadNotifications(currentUser.id);
			}
		} catch (notifErr) {
			console.warn('Notification dispatch warning:', notifErr);
		}

		// 8. Audit log
		try {
			db.logAction(
				currentUser?.id || 'system',
				'Vendor Invoice Dispatched to Admin',
				`Vendor ${resolvedVendorName} invoice ${nextInvNumber} (PO: ${poNumber}, ₹${totalAmount.toLocaleString()}) auto-generated upon Razorpay payment ${paymentId} and submitted to Admin.`
			);
		} catch (logErr) {
			console.warn('Audit log warning:', logErr);
		}

		return {
			success: true,
			invoice: newInvoice
		};
	} catch (err) {
		console.error('createAndSendVendorInvoice error:', err);
		return {
			success: false,
			error: err.message || 'Invoice generation error'
		};
	}
}
